- afl-fuzz.c
This change turns on by-default sink-holing of stdout/stderr output messages, it also adds an environment variable called AFL_NO_SINKHOLE that can be used for debugging purposes.
Cheers!
> afl-fuzz: sink-hole stdout/stderr

- afl-fuzz.c
This change computes a 64 bits (pseudo) randomized seed that will be used to name the shared section and the named pipes used to spawn the target.
Before this change, the names were hardcoded thus preventing a user to run several instances of afl-fuzz on the same machine.
Cheers!
> afl-fuzz: allow several slaveless instances to be run on the same machine

- CMakeLists.txt
- afl-showmap.c
This PR introduces afl-showmap for Windows - I've been trying it out for a bit of time now and has been working like a charm!
Cheers
> introducing Windows port of afl-showmap

- afl-fuzz.c
> Fix crash on zero sized input files

- afl-fuzz.c
- types.h
this patch adds support for affinity & fixes https://github.com/ivanfratric/winafl/issues/91
> Added support for processor affinity for afl-fuzz workers

- winafl.c
> Added support for catching STATUS_HEAP_CORRUPTION (0xC0000374)

- test.cpp
- winafl.c
Hey guys,
@ivanfratric  / @yoava333 please have a look :).
Cheers
> winafl/test: hook IsProcessorFeaturePresent/UnhandledExceptionFilter to be able to catch /GS stack-cookie overwrite exception (int 29h)

- CMakeLists.txt
- README.md
- afl-fuzz.c
- debug.h
> Added support for ansi terminal on windows 10

- CMakeLists.txt
> Fixed compilation issue on newer versions of DynamoRIO

- winafl-whatsup.py
> added winafl-whatsup.py a winafl replacement for afl-whatsup

- afl-fuzz.c
- afl-showmap.c
- afl-tmin.c
- debug.h
- winafl-plot.py
- winafl-whatsup.py
Just a few small fixes / additions that gathered in my local repo:
* added winafl-plot.py a winafl alternative for afl-plot & fixed compatibility issues with python3 in winafl-whatsup.py
* fixed a minor memory leak
* added console color support for afl-tmin and afl-showmap
> Minor fixes

- README.md
- afl-fuzz.c
Hi,
Following the discussion in https://github.com/ivanfratric/winafl/issues/71 here's a pull request that solves the issue
> Adding timeout for process initialize

- afl-fuzz.c
> Fix WinAFl timeouts loop

- gdiplus.cpp
> commented out unused code.

- afl-fuzz.c
This pull request allows the user to specify the CPU number for running the fuzzer.
> Add an option to specify CPU affinity

- afl-fuzz.c
This pull request allows custom payload delivery (e.g., via memory as opposed to always via file).
> Add dll_write_to_testcase_ptr callback

- README.md
- afl-fuzz.c
This PR allows to implement a customized mutation from a DLL
> Add dll_mutate_testcase_ptr

- README.md
> may20 cves

- README.md
- afl-fuzz.c
Update usage hints in afl-fuzz and supported options in README.md, and fix some minor typos.
> Update usage hints in afl-fuzz and supported options in README.md

- README.md
thanks ivan, without winafl it wont be possible.
> new cve in 2021

- winafl.c
If no_loop DynamoRIO mode was used and coverage was measured thread specific, threads that exit the target function would continue to measure their coverage.  The threads may do something nondeterministic before returning to the target function.  As an example, the target program could be a server that has a thread pool serving a REST API.  The target function could be a single API method that is served by the pool.  The tester would only be interested in the coverage of the target method.  After threads have returned from the target method to the queue, they could serve other methods that the fuzzer has to call to maintain the global state or they could do some timed background operations like logging thread inactivity or optimizing the size of the thread pool.  These operations would …
> Thread specific coverage measurement is stopped in no_loop after leaving target

- winafl-cmin.py
Sanity check: Ensure the target executable exists
> winafl-cmin: Add sanity check to ensure the target executable exists

- winafl-cmin.py
Make winafl-cmin compatible with Python 3. Changes were designed to still support Py2, to avoid breaking existing scripts.
> winafl-cmin: Support Python 3

- winafl-cmin.py
This change was made in error.
> winafl-cmin: Revert output directory check

- README.md
updates for shared memory mode.
> updates for shared memory mode.

- afl-fuzz.c
This PR attempts to fix CPU utilization stats by using PDH functions to retrieve the average usage of all processors.
> Fix CPU utilization stats

- afl-analyze.c
- afl-fuzz.c
- afl-showmap.c
- afl-tmin.c
- alloc-inl.h
- winaflpt.c
Fix a few compilation and static analysis warnings (which look correct and fairly trivial to fix)
> Fix warnings

- winafl-cmin.py
Various improvements to winafl-cmin.py
> Cmin improvements

- winafl.c
See: https://github.com/DynamoRIO/dynamorio/issues/5268
> Added report URL

- afl-tmin.c
- debug.h
Various improvements to afl-tmin (commit messages hold more elaboration)
> Tmin improvements

- winafl.c
Even with the cicd, I can not compile winafl.
This PR fixed the issue.
> PR to permit winafl to build on windows

- afl-tmin.c
turns out everything wasn't all good
> show the -w argument in the usage
