afl-fuzz.c

This change increments properly `optind` when dealing with options without parameters (switch on/off type of options).
Right now, `optind` is not incremented which makes the program loops forever, and might trigger this sort of error:
```cmd
D:\winafl-master\bin32>afl-fuzz.exe -d
WinAFL 1.03 by <ifratric@google.com>
Based on AFL 1.96b by <lcamtuf@google.com>
[-] PROGRAM ABORT : Multiple -d options not supported
Location : main(), ..\afl-fuzz.c:7210
```
Cheers

afl-fuzz: fix getopt to properly handle options without parameters

---

afl-fuzz.c

This is a very simple PR that deletes the childpid file created by drrun to allow afl-fuzz to grab the pid of the instrumented target. Once the file is read, it is of no use and can be deleted in order to keep the current "clean".
It is even more useful for the afl-cmin/showmap scenario where you instrument the target with a fuzz_iteration = 1, so you basically end up with one childpid file per samples which is very annoying.
Cheers

afl-fuzz: automatically remove the child pid file created by drrun to keep the directory clean

---

winafl.c

This commit replaces the case sensitive `strcmp` by the case insensitive equivalent function and logs more messages when using the debug mode.
I've had several times where the preferred module name happened to be in uppercase and/or different from the actual filename (assuming you have a debug record in the PE and in this case this name will be used instead); debugging this can be a little bit annoying as the debug mode did not log any information related to the coverage settings which is what I'm trying to address here.
Let me know if you think using `_stricmp` might lead to issues I haven't thought about :).
Cheers

winafl: use a case insensitive string compare function, and ease debugging coverage related settings with extra logging messages

---

winafl.c

This PR modifies winafl so that it uses the executable name as the name of the module - as opposed to the "preferred" name. The preferred name can be found in the PE headers of the executable in the Debug directory for some of them.
One example is to take 'test.exe', to rename it to 'foo.exe'; winafl will still consider the module 'foo.exe' as 'test.exe' which is super annoying and confusing.

winafl: use exe_name instead of the preferred name

---

CMakeLists.txt

Small Patch for VS2015. Please let me know if you'd like a VC >= 1900 check statement before the target_link_libraries statement. 
Related Issue: https://github.com/ivanfratric/winafl/issues/10
Thanks!

VS2015 Fix

---

winafl-cmin.py

This PR introduces the first version of winafl-cmin.py which can be used to generate minset of corpuses based on the instrumentation generated by winafl. It plays nicely with WinAFL, and tries to use the same option names, etc. so that users already using afl-fuzz.exe can pick up this one very easily.
The script is currently not fully feature complete, it at least doesn't support passing testcases via stdin - I've only used it on target that takes filename so far.
Here is what looks like the help section:
```
$ python winafl-cmin.py -h
corpus minimization tool for WinAFL by <0vercl0k@tuxfamily.org>
Based on WinAFL by <ifratric@google.com>
Based on AFL by <lcamtuf@google.com>
usage: winafl-cmin.py [-h] -i dir -o dir [-n] [--working-dir dir] [-v]
[-covtype {edge,bb}]
[-call_convention …
```

introduce winafl-cmin.py

---

afl-fuzz.c

I've started to play with winafl so take this pull request carefully, I could be wrong, feedback is welcome =)
The changes:
* Use ```ck_alloc_nozero```  instead of ```malloc``` to allocate the ```orig_in``` memory in ```fuzz_one```. I'm not really sure if there is a good reason to use plain ```malloc``` instead of "ck_alloc_nozero". I could be missing it, feel free to say :). Since original afl uses mmap and checks for errors I guess using "ck_alloc_nozero" could be a good idea :)
```
orig_in = in_buf = mmap(0, len, PROT_READ | PROT_WRITE, MAP_PRIVATE, fd, 0);
if (orig_in == MAP_FAILED) PFATAL("Unable to mmap '%s'", queue_cur->fname);
```
* free orig_in: Original afl takes care of unmap'ing ```orig_in``` before returning from ```fuzz_one```:
```
munmap(orig_in, queue_cur->len);
if (in_buf …
```

Allocate and free orig_in with ck_* methods

---

afl-fuzz.c
afl-showmap.c
config.h

This PR introduces a bunch of bug-fixes, and various improvements coming from the versions > 1.96b (stability indicator, parallelizing of deterministic steps, aflfast tweaks, etc.).
Here are the different commits I've ported:
- 2.02b: https://github.com/mirrorer/afl/commit/13c63f858c5f8d72d160a6bfe6d58928948d1597
- 2.11b: https://github.com/mirrorer/afl/commit/12eeeeaf48576c925db5013fa8dd4613649de144
- 2.18b: https://github.com/mirrorer/afl/commit/81680ec6c09b99aa76e6241533fe9706e00703dd
- 2.20b: https://github.com/mirrorer/afl/commit/8b3079a5fe75242f3c9300ece0833e3a1a04b0c9
- 2.21b: https://github.com/mirrorer/afl/commit/8b3079a5fe75242f3c9300ece0833e3a1a04b0c9
- 2.22b: https://github.com/mirrorer/afl/commit/2e8d7564af707f0693a346a8d39e2effb409099d
- 2.23b: …

Porting AFL improvements to WinAFL.

---

afl-fuzz.c

In the previous set of changes, I unfortunately messed up and got rid of the slave mode, oops; this change re-adds it.
Cheers

afl-fuzz: fix the slave mode

---

afl-fuzz.c

last_crash_time is missing probably due to porting from afl

Fixed missing last_crash_time

---

winafl-cmin.py

This PR adds three minor winafl-cmin improvements:
1. Honor the AFL_NO_SINKHOLE environment variable; very useful to debug
1. Add the --skip-dry-run flag to carry on corpus minimization even if the two executions of the harness generated different coverage maps
1. Output an error message if the user has forgotten to specify the marker '@@' somewhere (very annoying to debug)
Cheers

Minor winafl-cmin improvements.

---

CMakeLists.txt
README.md
afl-tmin.c

This PR adds afl-tmin for Windows supporting both syzygy / DRIO instrumented target:
```
D:\Codes\winafl\buildx86\RelWithDebInfo>afl-tmin.exe -Y -i ..\..\testcases\tests\big.txt -o big.min.txt -- test_static.instr.exe @@
afl-tmin for Windows 2.51b by <0vercl0k@tuxfamily.org>
Based on WinAFL 2.51b by <ifratric@google.com>
Based on AFL 2.51b by <lcamtuf@google.com>
[+] Read 552 bytes from '..\..\testcases\tests\big.txt'.
[*] Performing dry run (mem limit = 0 MB, timeout = 1000 ms)...
[+] Program terminates normally, minimizing in instrumented mode.
[*] Stage #0: One-time block normalization...
[+] Block normalization complete, 552 bytes replaced.
[*] --- Pass #1 ---
[*] Stage #1: Removing blocks of data...
Block length = 64, remaining size = 552
Block length = 32, remaining size = 40
Block …
```

introducing the afl-tmin port for Windows.

---

afl-fuzz.c
debug.h

The definition of `ENABLE_VIRTUAL_TERMINAL_PROCESSING` should be in `debug.h` instead of `afl-fuzz.c` to compile on old version of Windows SDKs.

Fix ENABLE_VIRTUAL_TERMINAL_PROCESSING undefined

---

README.md
afl-fuzz.c
test.cpp
winafl.c

Hey, I've just added a new switch to winafl: -fuzz_mode in_app_persistent
it will take the normal target_module and target_function/target_offset and hook it into a pre_loop_start_handler instead the pre_fuzz_handler and post_fuzz_handler as we discussed.
If you disagree with something or has any suggestions to make it even better, let me know

implemented in_app_persistent_mode

---

CMakeLists.txt
README.md
afl-fuzz.c
config.h
test_netmode.cpp
winafl.c

This commit enables network-based applications fuzzing over TCP and UDP protocols.
This commit has test application to verify that network-based fuzzing actually works.

Enable network fuzzing support for winAFL

---

CMakeLists.txt
README.md
afl-fuzz.c
config.h
custom_net_fuzzer.c
custom_winafl_server.c
custom_winafl_server.cpp
custom_winafl_server.h
test_netmode.cpp
test_simple_winsock_client.cpp
winafl.c

1) WinAFL now supports server mode fuzzing to test clients. User need to specify a third-party DLL where he/she should define communication logic with a client.
2) Added default server DLL for winAFL.
3) Added test for server-mode fuzzing support.

Added server mode fuzzing support in winAFL

---

afl-showmap.c

afl-showmap show the wrong `target_path` in drioless mode.

Fix target_path in drioless mode

---

afl-staticinstr.c

This pull request fixed a communication bug where afl-staticinstr fails to send the "P" command expected by afl-fuzz.exe.

Fix a protocol broken issue

---

CMakeLists.txt
afl-fuzz.c
custom_net_fuzzer.def
custom_winafl_server.def

This pull requests allows the custom DLL to export its own run_target implementation to make future fuzzing modes support more extensible.

Allow custom dll to export its run_target

---

afl-fuzz.c
config.h
hash.h
types.h

Because  __x86_64 is a macro used under linux,  i replace it  with  _WIN64 that can be  used under windows

Replace __x86_64  as _WIN64

---

afl-fuzz.c

With intelpt set to gather coverage during fuzzing scenario it was impossible to start more than instance using -M / -S because winaflpt.c:751 add_module_to_section_cache() function was trying to overwrite module cache that was already in use resulting in error: "Error opening image cache file.".
To avoid this problem I've moved modules_dir inside master/slave sync dir.

Fixed ptmodules directory collision

---

winafl.c

Since on Windows FS is case-insensitive by default, it does not make sense to compare module names case-sensitively.
This patch is based on my experience. Latest version of WinAFL fails to fuzz my binary in DynamoRIO mode since it imports library `ABC.dll` and not `abc.dll`. Somehow even if you explicitly set target module to `ABC.dll` it still fails to find it. Changing `strcmp` to `_stricmp` in `event_module_load` fixed this. Other two `strcmp` were replaced using same logic.

use _stricmp consistently when comparing module names

---

afl-fuzz.c

When resuming sessions, winafl can't restore the queue position and timeout value from the older fuzzing job, because the substring patterns in strstr() don't match with the ones in fuzzer_stats file.

Fix wrong substring patterns

---

CMakeLists.txt

Starting from VS2019 target platform (Win32/x64) is passed to cmake as a separate argument -A (architecture) and ends up in CMAKE_GENERATOR_PLATFORM variable rather than part of CMAKE_GENERATOR.

Support x64 build with VS2019

---

afl-fuzz.c
winafl.c

thanks ivan. closing my previous pull request and opening this new request as per the changes suggested by you. please review and let me know if its ok now.
1. added a global DWORD ret_exception_code.
2. added new functions ReadDWORDFromPipe in afl-fuzz.c and WriteDWORDCommandToPipe in winafl.c
3. added switch for exception names in save_if_interesting function.

crash codes

---

afl-fuzz.c

* The env_variable `AFL_NO_AFFINITY` should be detected before checking the `cpu_core_count`.
* The option `-c` and env_variable `AFL_NO_AFFINITY` are mutually exclusive.

FIX: the environment variable AFL_NO_AFFINITY doesn't work

---

afl-fuzz.c

`cycles_wo_finds` (cycles without any new paths) should be reset when appending new test case.

FIX: cycles_wo_finds should be reset when appending new test case

---

afl-fuzz.c

When calibrating the test case, `first_trace` is used to compare against repeated runs of new queue entries, but the contents of `first_trace` was not added to the discovered bits, which can lead to the negative "stability" UI bug. (refer to [AFL#54](https://github.com/google/AFL/issues/54))

FIX: negative value of stability

---

afl-fuzz.c

* The specified CPU core should be less than 64 (winafl doesn't support more than 64 cores at the moment).
* The specified CPU core should be not allocated.

Add check for specifying CPU affinity

---

afl-fuzz.c

When resuming sync fuzzers:
* the out dirs of synced fuzzers should not be deleted
* do not need to setup new out dirs

FIX: some problems when resuming sync fuzzers

---

README.md

The build documentation in README is out of date for VS 2019.
The current documentation causes this issue:
```
CMake Error: Could not create named generator Visual Studio 16 2019 Win64
Generators
* Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
Use -A option to specify architecture.
Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
Optional [arch] can be "Win64" or "ARM".
...
```
I attempted to fix this originally by switching from `cmake -G"Visual Studio 15 2017 Win64"` to `cmake -G"Visual Studio 1 2019" -A Win64`, but that caused another error.
I discovered the fix of using `-A x64` instead from [here](http://cmake.3232098.n2.nabble.com/Can-t-Generate-Project-Files-for-VS2019-td7599413.html).
My commit for 32 bit may not be correct. …

Documentation Update - VS2019 & README

---

README.md
afl-fuzz.c

The user-provided mutation function is a great feature in WinAFL.  However, if it is used as a replacement for both the deterministic and havoc mutations, it should use an energy value that determines how many mutants to create from the input.  This allows the genetic algorithm to prioritize some queue items.  The havoc stage uses a similar value.  The energy was set to the value used by havoc if the deterministic mutations are skipped.
The custom mutator is expected to implement the looping. For example, if the mutator must somehow parse the input data before mutating it, it can be done once before starting the loop. This should be faster than looping `dll_mutate_testcase_ptr` in afl-fuzz.c.

User-provided mutation function with energy

---

afl-fuzz.c

As mentioned in comment https://github.com/googleprojectzero/winafl/pull/241#issuecomment-654811943, trimming may not be compatible with custom mutators. For example, if the mutator uses libprotobuf-mutator, the trimming would make the input Protobuf messages invalid.
I added an option for a user-provided trimming function that could be used to trim test cases while keeping them valid for the mutator.  The function can also be used to skip trimming by implementing a function that just returns 0.

User-provided trimming function.

---

winafl-cmin.py

Add two new command-line arguments --crash-dir and --hang-dir
--crash-dir allows specifying a directory in which all crashes encountered should be stored in
--hang-dir allows specifying a directory in which all hangs encountered should be stored in

winafl-cmin: Add --crash-dir and --hang-dir

---

afl-fuzz.c

Following changes has been made to support shared memory:
1. added a new command line option : -a if set with any value it will enable shared memory mode. ex: afl-fuzz.exe -a yes
2. used createfilemapping calls for shared memory.
3. modified options if shared memory then output file will be shmem.
4. will be unmapped at exit.

adding shared memory support.

---

README.md
afl-fuzz.c
config.h
winafl.c

Using the new [DynamoRIO attach functionality](https://github.com/dynamorio/dynamorio/issues/725) to allow fuzzing of targets that we cannot simply run (e.g. services).
We identify the target process as the first process we find that loaded a specified module. 
For future use-cases it might be beneficial to add the possibility to identify the target by the command line (or maybe allow custom identification).
We kill the target as usual, but we do not restart it. I am not sure there is a use-case for it (for example for a service, one may simply define it as auto-restarting or run a script that keeps it alive). But if there is a use-case maybe it would be best to call a custom restart function as well.
Based on [this RDP fuzzing project](https://www.cyberark.com/resources/threat-research-bl …

use DR attach functionality

---

winafl-cmin.py

This PR fixes the `--edges-only` option of `winafl-cmin.py` as the `-e` switch should be passed to `afl-showmap.exe` in the first group before the instrumentation options, otherwise the DynamoRIO client will throw an `unrecognized option` error.

Fix --edges-only option used to ignore hit counts

---

README.md
afl-fuzz.c
readme_dr.md

This PR switches from using WinAFL as a simple client (`drrun.exe -c winafl.dll -- notepad`) to using it as a pre-configured tool (`drrun.exe -t winafl -- notepad`) to run alongside DynamoRIO.
> A tool is a client with a configuration file that sets the client options and path, providing a convenient launching command via the `-t` parameter.
A [tool](https://dynamorio.org/page_deploy.html#tool_frontend) can be configured by creating a file in the `tools` subdirectory of the root of the DynamoRIO installation called  `winafl.drrun32` or  `winafl.drrun64`, depending on the target architecture. The `CLIENT_ABS` or `CLIENT_REL` specifiers enable `drrun` to locate the `winafl.dll` client library. 
As an example for a 32-bit build, the configuration file should contain at least the following …

Add support for using WinAFL as a pre-configured tool for DynamoRIO

---

afl-analyze.c
afl-fuzz.c
afl-showmap.c
afl-tmin.c
config.h

This PR backports the following bug fixes or improvements from the AFL and AFL++ projects:
- Fix next_100 pointers by google/AFL@fab1ca5ed7e3552833a18fc2116d33a9241699bc
- Fix counting stage execs for user inserts by google/AFL@2abd3f4041269d1a64562e31147078234542dc9b
- Fix the issue with testcase calibration failure not being respected by google/AFL@ee6ffe6347fc282d7bb6f0d869acb37c74ea8ef8
- Add option -V: Show version number and exit by google/AFL@fcf734aab735b0e6652aa9f549ba41c0fde05d4d
- Add file permission setting to config.h by AFLplusplus/AFLplusplus@dfe6f7f8c949744eeab7a401affde93729a5b39d

Backporting AFL improvements to WinAFL

---

afl-fuzz.c

This PR attempts to fix an error due to `unlink` failing when updating a test case after trimming by falling back to truncating the file. AFL++ follows a similar approach using an additional `-N` flag added by AFLplusplus/AFLplusplus@f8bc9b54dabc759e9ad1eb82e5ee36af3bb4e1a6.

Fix error when writing trimmed test case

---

afl-fuzz.c
afl_docs/env_variables.txt
winafl-plot.py

This PR backports some improvements for in-place resume from the AFL++ project. It adds `run_time` and `prev_run_time` and applies them in time calculations for the UI, `fuzzer_stats` and `plot_data`.
Furthermore, it adds an `AFL_AUTORESUME` environment variable to enable automatically resuming a fuzzing session, if an output directory already exists and also loads some variables from the existing `fuzzer_stats` file.
The related backported commits are the following:
- Preserve `plot_data` for in-place resume by AFLplusplus/AFLplusplus@62508c3b446a893f0afead9a6d0546d53d588a13
- Update `plot_data` with relative timestamps when resuming by AFLplusplus/AFLplusplus@7e67a735e6a30550288fc8c35541f91ea4cf3de3
- Load `prev_run_time` from `fuzzer_stats` when resuming by …

Backporting AFL++ improvements for in-place resume

---

afl-tmin.c

Print total run time in the summary (on success). Useful for getting an idea of the performance of the harness, especially when runtime is long (minutes-hours)

Print total run time in the summary

---

afl-analyze.c
afl-fuzz.c
afl-showmap.c
afl-tmin.c

Disk I/O is the bottleneck for fast harnesses (verified by profiling). Reducing the amount of those calls should give us an immediate performance gain.
I apologize but I won't have time to test this change, as I need to start a project at work, but if something seems amiss tell me and I'll try to make some time to fix it.

Remove redundant file API calls (unlink before open, seek before close)

---

afl-fuzz.c

I tried custom mutator functionality as readme, and implemented the "dll_muate_testcase" function. However, I found my custom mutator was never called, so I looked at the source code of winafl and found a minor bug in the following code.
```
// Prefer a custom mutator that accepts the performance score as an energy value.
if (dll_mutate_testcase_with_energy_ptr)
if (dll_mutate_testcase_with_energy_ptr(argv, in_buf, len, perf_score, common_fuzz_stuff))
goto abandon_entry;
else if (dll_mutate_testcase_ptr)
if (dll_mutate_testcase_ptr(argv, in_buf, len, common_fuzz_stuff))
goto abandon_entry;
```
It seems like WinAFL intends to call a custom mutator function if either 'dll_mutate_testcase_with_energy' or 'dll_mutate_testcase' function is given by a user. However, "dll_mutate_testcase" is …

Fixed the issue that custom mutator function is not invoked

---

afl-fuzz.c

Hi @ifratric, I'm very excited to see TinyInst support in WinAFL.
I compiled WinAFL with support for TinyInst and ran into some problems initially. The first debug step I did was to run winafl and check the help menu. I was looking for the `-y` option but it wasn't there. The next thing I did was look at the version and compare with older builds. Neither of these helped me determine if I actually compiled in TinyInst support so I inspected the binary with IDA to confirm.
I proposing a few changes to help others who may face the same situation:
- bump WINAFL_VERSION to indicate support for TinyInst
- Add `-y` option to usage message

Update help / usage message

---

afl-tmin.c

fixes #179 so that afl-tmin.exe can run from a different directory than the one winafl.dll is in

allow the winafl.dll path to be specified by -w in afl-tmin.exe

---

afl-fuzz.c

Changed custom library loading to also load dependencies from the directory that contains the custom library.

Load custom library dependencies from same directory
